spring:
  datasource:
    # LƯU Ý: Nếu chạy trong Docker, localhost phải đổi thành postgres-db
    url: jdbc:postgresql://postgres-db:5432/authdb?options=-c%20timezone=Asia/Ho_Chi_Minh
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}

  # PHẢI NẰM TRONG SPRING
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

logging:
  level:
    com.chatapp.api_gateway.util: INFO

jwt:
  secret: "${JWT_SECRET}"
  expiration-ms: 86400000