server:
  port: 8080

logging:
  level:
    com.chatapp.api_gateway.util: INFO
    org.springframework.cloud.gateway: INFO

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. AUTH SERVICE (Đã bỏ StripPrefix)
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        # 2. CHAT SERVICE - Lấy tin nhắn
        - id: chat-service-messages
          uri: http://chat-service:8082
          predicates:
            - Path=/messages/**
          filters:
            - AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        # 3. CHAT SERVICE - Lấy danh sách phòng
        - id: chat-service-rooms
          uri: http://chat-service:8082
          predicates:
            - Path=/rooms/**
          filters:
            - AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        # 4. CHAT SERVICE - WebSocket
        - id: chat-service-ws
          uri: http://chat-service:8082
          predicates:
            - Path=/ws/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

jwt:
  secret: "mysecretkey123456789012345678901234"

eureka:
  client:
    enabled: false