server:
  port: 8080

logging:
  level:
    com.chatapp.api_gateway.util: INFO

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        # 1. AUTH SERVICE
        - id: auth-service
          uri: http://auth-service:8081 # Đúng (vì Auth Service đã sửa thành 8081)
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1 # <--- THÊM VÀO: Biến /api/auth thành /auth

        # 2. CHAT SERVICE (HTTP)
        - id: chat-service
          uri: http://chat-service:8082
          predicates:
            - Path=/api/chat/**
          filters:
            - AuthenticationFilter
            - StripPrefix=1 # <--- THÊM VÀO

        # 3. CHAT SERVICE (WS)
        - id: chat-service-ws
          uri: ws://chat-service:8082
          predicates:
            - Path=/ws/**
            # filters:
            # - AuthenticationFilter (Tạm đóng khi dev để dễ test socket)

jwt:
  secret: "${JWT_SECRET}"

eureka:
  client:
    enabled: false