server:
  port: 8082

spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://chat-mongo:27017/chatdb
      auto-index-creation: true
  cloud:
    compatibility-verifier:
      enabled: false
# --- SỬA ĐOẠN NÀY ---
# Đưa ra ngoài cùng, không nằm thụt vào trong 'spring'
application:
  config:
    # Biến này sẽ hứng giá trị từ Docker (NOTIFICATION_SERVICE_URL)
    notification-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}